# Generated by Django 4.1.2 on 2022-11-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="has_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Webapp.ticket",
            ),
        ),
    ]
