# Generated by Django 4.1.2 on 2022-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_ticket_has_response_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[('', 0), ('★', 1), ('★★', 2), ('★★★', 3), ('★★★★', 4), ('★★★★★', 5)]),
        ),
    ]
